### ISSUE TITLE
Access to other OAuth2 tokens (refresh_token & id_token)

### ISSUE THREAD

**Issue by ljovanovic** [workato/connector_sdk#102]
I see in the various OAuth2 examples how to access the access_token returned from an OAuth2 authorization server, however I have not been able to see any way to access other portions of that payload, such as the id_token or refresh_token. 

Is this possible presently?  Appreciate any thoughts.

**Comment by eeshan92** [comment]
@ljovanovic the default behaviour of the SDK picks up values linked to `access_token` and `refresh_token` keys respectively. To handle variations of the keys, you will need to use a custom OAuth connection. Update to our docs is in PR [here](https://github.com/workato/docs/pull/257)

**Comment by eeshansim** [comment]
@ljovanovic This is possible using custom OAuth2, see example in documentation [here](http://docs.workato.com/developing-connectors/sdk/authentication/oauth2-authentication.html#custom-token-authentication).

Closing this
