### ISSUE TITLE
Developer site UI does not display correctly when search returns no results

### ISSUE THREAD

**Issue by bryanyap** [workato/connector_sdk#142]
![screen shot 2018-07-17 at 2 18 13 pm](https://user-images.githubusercontent.com/5821001/42846023-867d639e-89cc-11e8-913b-100309330335.png)

**Comment by sharat-developer** [comment]
@ctjsctjs ˆˆ

**Comment by ctjsctjs** [comment]
@bryanyap Added no results message. https://github.com/workato/connector_sdk/pull/143/commits
