### ISSUE TITLE
SDK: SalesforceIQ (S2 - Testing)

### ISSUE THREAD

**Issue by Brendon395** [workato/connector_sdk#93]
Connection issue:
Was unable to create a connection in the recipe page, encountered a "Connection failed: Test failed due to server error"
Able to create a connection from the connections tab.
Edit 1: No longer an issue creating a connection from recipe page.

Trigger: New/Updated Account
![image](https://user-images.githubusercontent.com/29088705/30908128-4369f742-a3af-11e7-82b3-da4c65c4bf0e.png)
Issue 1: Formatting error - No space between "in" and "SalesforceIQ"
Issue 2: Since field - Not working as expected. Records that should've been excluded are being picked up. In addition, field hint could be clearer. Suggest: "Date and time to pickup the first record from. Leave blank to start when recipe is run. **Once recipe has been run or tested, value cannot be changed.**

Action: Create account
Issue: City, State/Province, Zip/Postal Code, Country are not reflected in the address. Seems like it is a problem with SalesforceIQ API. If so, we should notify users about it, and either remove these fields or to include an action hint to include the full address in the address bar. 
Edit 1: No longer an issue with the 4 fields.

Action: Search account
Issue 1: Include an action hint. Suggest: "Returns a list of accounts matching the IDs to search for. If blank, returns a list of all accounts."
![image](https://user-images.githubusercontent.com/29088705/30908716-09881ed0-a3b1-11e7-81ae-4b6b09864dbe.png)
Issue 2: Formatting error - No space between "in" and "SalesforceIQ"

Resources:
https://api.salesforceiq.com/#create-an-account

**Comment by svchandra** [comment]
Connection issue:
Ensure connection name should be unique, it is framework restriction. if already connection exist's the throws Internal Server error.
Trigger:
Issue1: space issue is fixed.
Issue2: **Once recipe has been run or tested, value cannot be changed.** - this will be appended by framework. not required to provide in the adapter.

Actions:
Create Account: City, Province, State, Code are non editable fields, so ignored in the recipe action input.
Search Accounts:
Issue1: fixed.
Issue2: fixed.
